# This is a basic CI (Continuous Integration) workflow file that will perform
# basic testing on the PHP and Dockerfile code that gets updated here.

# Note that extra steps would be needed to test the bash and PowerShell code.

# Tabs are not allowed in yaml.
name: CI

on:
  push:
    branches:
      - main
        # Right now, this rule applies only to the main branch.
  pull_request:
    # Nothing for pull requests (merging changes others have made)

  workflow_dispatch:
    # Used for manually executing CI.

jobs:
  validate:
    # Required testing environment.  Also known as a "build runner."
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5 # Copies code into the "ubuntu-latest" testing environment.

      - name: Setup PHP
        uses: shivammathur/setup-php@v2 # A specialized PHP testing environment.
        with:
          php-version: '8.3'

      - name: Check PHP Syntax
        run: |
          find . -name "*.php" -exec php -l {} \;

      - name: Build Container
        run: |
          docker build -t api-demo .

      - name: Start Container
        run: |
          docker run -d -p 60080:80 --name api-demo api-demo

      - name: Add required hostname mapping.  Note that we want to show the output as well as update the hosts file.
        run: |
          echo "127.0.0.1 my-api-demo" | sudo tee -a /etc/hosts

      - name: Verify hostname mapping
        run: |
          getent hosts my-api-demo
          ping -c 1 my-api-demo

      - name: Browse API Default Page
        run: |
          curl --fail http://my-api-demo:60080/index.php

      # Note that the quotes-examples.php file includes the file api-key.txt, so it should be able to run successfully here.
      - name: Generate API Key and Save to File
        run: |
          curl -f -X POST --data "Submitting=1&keyOnly=1" http://my-api-demo:60080/make-access-token.php > api-key.txt

      - name: Display the Generated API Key
        run: |
          cat api-key.txt

      - name: List the files.
        run: |
          ls -al

      # quotes-validate.sh tests essentially the same thing as quotes-examples.sh, but it's geared more for CI.
      - name: Run the quotes-validate.sh file.  This must have a 0 exit value or the workflow fails.
        run: |
          chmod +x ./quotes-validate.sh; ./quotes-validate.sh

      # Check for runtime errors.  Note that the log file is inside of the container running on the runner, not directly on the runner itself.
      - name: Copy the error log out of the container and check for any PHP errors in the log.
        run: |
          docker cp api-demo:/var/log/apache2/api_error.log ./api_error.log
          ls -al
          #grep '\[php:error\]' /var/log/apache2/api_error.log > errors.txt
          if [ -s errors.txt ]; then 
            echo "Errors Found:"
            cat api_error.log
            exit 1
          else 
            echo "No errors found";
            exit 0
          fi
